---
spring:
  profiles:
    active: default
    include: dev

---
#spring:
#  profiles:
#    active: aws
#    include: aws

---
spring:
  config:
    import: env.yml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
springdoc:
  swagger-ui:
    path: /funfund.html

#google:
#  client-id: ${DEV_GOOGLE_CLIENT_ID}

#jwt:
#  access-secret-key: ${JWT_ACCESS_SECRET_KEY}
#  refresh-secret-key: ${JWT_REFRESH_SECRET_KEY}
#  access-expire-time-in-minutes: 30
#  refresh-expire-time-in-minutes: 1440

server:
  port: 8080