---
spring:
  profiles:
    active: default
    include: dev

---
#spring:
#  profiles:
#    active: aws
#    include: aws

---
spring:
  config:
    import: env.yml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /funfund.html

server:
  port: 8080
  ssl:
    enabled: true
    key-alias: local_ssl
    key-store: classpath:local-ssl.p12
    key-store-type: PKCS12
    key-password: 16022002
    key-store-password: 16022002